version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[transformers]]
name = "google-java-format"
enabled = true